[connections.telecom]
    type="sql"
    dialect="postgresql"
    username="postgres"
    password="jack"
    host="localhost" # IP or URL
    port= 5432 # Port number
    database="telecom" # Database name

    